/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('workflow_steps').del();
  await knex('appointments').del();
  await knex('visits').del();
  await knex('patients').del();

  await knex('patients').insert([
    {
      id: 'p1',
      name: 'Dewi Rahmawati',
      dateOfBirth: '1989-07-15',
      gender: 'Female',
      phone: '+62 812-3456-7890',
      address: 'Jl. Sudirman No. 12, Jakarta',
      allergies: JSON.stringify(['Penicillin']),
      tags: JSON.stringify(['BPJS', 'Hipertensi']),
      notes: 'Perlu cek tekanan darah setiap kunjungan.',
    },
    {
      id: 'p2',
      name: 'Budi Santoso',
      dateOfBirth: '1975-11-03',
      gender: 'Male',
      phone: '+62 811-2389-555',
      address: 'Jl. Diponegoro No. 8, Bandung',
      allergies: JSON.stringify([]),
      tags: JSON.stringify(['Asma']),
      notes: 'Membawa inhaler sendiri.',
    },
    {
      id: 'p3',
      name: 'Siti Nur Aisyah',
      dateOfBirth: '1994-02-21',
      gender: 'Female',
      phone: '+62 822-9911-2200',
      address: 'Jl. Taman Siswa No. 5, Yogyakarta',
      allergies: JSON.stringify(['Seafood']),
      tags: JSON.stringify(['Kehamilan']),
      notes: 'Trimester kedua, jadwal kontrol 2 minggu sekali.',
    },
    {
      id: 'p4',
      name: 'Andi Wijaya',
      dateOfBirth: '1982-05-12',
      gender: 'Male',
      phone: '+62 813-1122-3344',
      address: 'Jl. Merdeka No. 45, Surabaya',
      allergies: JSON.stringify(['Dust']),
      tags: JSON.stringify(['Diabetes']),
      notes: 'Kontrol rutin gula darah.',
    },
    {
      id: 'p5',
      name: 'Eka Putri',
      dateOfBirth: '1998-09-30',
      gender: 'Female',
      phone: '+62 856-4455-6677',
      address: 'Jl. Pemuda No. 21, Semarang',
      allergies: JSON.stringify([]),
      tags: JSON.stringify(['Checkup']),
      notes: 'Pasien baru.',
    },
    {
      id: 'p6',
      name: 'Faisal Akbar',
      dateOfBirth: '1990-12-15',
      gender: 'Male',
      phone: '+62 812-8899-0011',
      address: 'Jl. Gatot Subroto No. 34, Medan',
      allergies: JSON.stringify(['Aspirin']),
      tags: JSON.stringify(['Orthopedi']),
      notes: 'Pasca operasi lutut.',
    },
    {
      id: 'p7',
      name: 'Gita Lestari',
      dateOfBirth: '1985-03-08',
      gender: 'Female',
      phone: '+62 821-2233-4455',
      address: 'Jl. Imam Bonjol No. 9, Makassar',
      allergies: JSON.stringify(['Lactose']),
      tags: JSON.stringify(['Pencernaan']),
      notes: 'Sering keluhan lambung.',
    },
    {
      id: 'p8',
      name: 'Hadi Saputra',
      dateOfBirth: '1970-06-25',
      gender: 'Male',
      phone: '+62 811-3344-5566',
      address: 'Jl. Ahmad Yani No. 56, Malang',
      allergies: JSON.stringify([]),
      tags: JSON.stringify(['Jantung']),
      notes: 'Kontrol setelah pasang ring.',
    },
    {
      id: 'p9',
      name: 'Indah Permata',
      dateOfBirth: '1992-08-14',
      gender: 'Female',
      phone: '+62 857-1122-3344',
      address: 'Jl. Kartini No. 12, Solo',
      allergies: JSON.stringify(['Nuts']),
      tags: JSON.stringify(['Alergi']),
      notes: 'Butuh tes alergi lengkap.',
    },
    {
      id: 'p10',
      name: 'Joko Widodo',
      dateOfBirth: '1965-01-01',
      gender: 'Male',
      phone: '+62 812-7788-9900',
      address: 'Jl. Slamet Riyadi No. 1, Surakarta',
      allergies: JSON.stringify([]),
      tags: JSON.stringify(['Eksekutif']),
      notes: 'General checkup rutin tahunan.',
    },
  ]);

  await knex('visits').insert([
    {
      id: 'v1',
      patientId: 'p1',
      date: '2025-01-05T09:00:00+07:00',
      doctor: 'dr. Aditya',
      reason: 'Kontrol hipertensi',
      notes: 'Tekanan darah 130/85, lanjutkan obat.',
      prescription: 'Amlodipine 5mg',
    },
    {
      id: 'v2',
      patientId: 'p2',
      date: '2024-11-22T13:30:00+07:00',
      doctor: 'dr. Ratna',
      reason: 'Kontrol asma',
      notes: 'Tidak ada serangan baru.',
      prescription: 'Controller inhaler 2x sehari',
    },
    {
      id: 'v3',
      patientId: 'p3',
      date: '2024-12-30T11:00:00+07:00',
      doctor: 'dr. Yani',
      reason: 'Kontrol kehamilan',
      notes: 'Janin sehat, lanjutkan vitamin.',
      prescription: 'Vitamin prenatal',
    },
    {
      id: 'v4',
      patientId: 'p4',
      date: '2025-01-10T10:00:00+07:00',
      doctor: 'dr. Aditya',
      reason: 'Cek gula darah',
      notes: 'Gula darah puasa 110, stabil.',
      prescription: 'Metformin 500mg',
    },
    {
      id: 'v5',
      patientId: 'p6',
      date: '2025-01-12T14:00:00+07:00',
      doctor: 'dr. Lukman',
      reason: 'Fisioterapi',
      notes: 'Mobilitas meningkat 20%.',
      prescription: 'Gel pereda nyeri',
    },
    {
      id: 'v6',
      patientId: 'p7',
      date: '2025-01-15T09:30:00+07:00',
      doctor: 'dr. Ratna',
      reason: 'Sakit perut',
      notes: 'Gejala maag akut.',
      prescription: 'Antasida & Omeprazole',
    },
    {
      id: 'v7',
      patientId: 'p8',
      date: '2024-12-20T11:00:00+07:00',
      doctor: 'dr. Gunawan',
      reason: 'Post-op checkup',
      notes: 'Jantung stabil, ritme normal.',
      prescription: 'Blood thinner',
    },
    {
      id: 'v8',
      patientId: 'p9',
      date: '2025-01-18T13:00:00+07:00',
      doctor: 'dr. Yani',
      reason: 'Ruam kulit',
      notes: 'Alergi makanan ringan.',
      prescription: 'Cetirizine',
    },
    {
      id: 'v9',
      patientId: 'p5',
      date: '2025-01-08T08:30:00+07:00',
      doctor: 'dr. Aditya',
      reason: 'Demam',
      notes: 'Flu biasa.',
      prescription: 'Paracetamol',
    },
    {
      id: 'v10',
      patientId: 'p10',
      date: '2024-12-05T09:00:00+07:00',
      doctor: 'dr. Lukman',
      reason: 'Konsultasi gaya hidup',
      notes: 'Saran diet rendah garam.',
      prescription: 'Multivitamin',
    },
  ]);

  await knex('appointments').insert([
    {
      id: 'a1',
      patientId: 'p1',
      date: '2026-02-15T08:00:00+07:00',
      reason: 'General check',
      status: 'scheduled',
    },
    {
      id: 'a2',
      patientId: 'p2',
      date: '2026-02-16T10:30:00+07:00',
      reason: 'Spirometri',
      status: 'scheduled',
    },
    {
      id: 'a3',
      patientId: 'p3',
      date: '2026-02-15T09:15:00+07:00',
      reason: 'Kontrol kandungan',
      status: 'scheduled',
    },
    {
      id: 'a4',
      patientId: 'p4',
      date: '2026-02-17T14:00:00+07:00',
      reason: 'Konsultasi Gizi',
      status: 'pending',
    },
    {
      id: 'a5',
      patientId: 'p5',
      date: '2026-02-18T11:00:00+07:00',
      reason: 'Follow up flu',
      status: 'scheduled',
    },
    {
      id: 'a6',
      patientId: 'p6',
      date: '2026-02-19T13:00:00+07:00',
      reason: 'Rehabilitasi medik',
      status: 'scheduled',
    },
    {
      id: 'a7',
      patientId: 'p7',
      date: '2026-02-15T15:30:00+07:00',
      reason: 'Endoskopi',
      status: 'pending',
    },
    {
      id: 'a8',
      patientId: 'p8',
      date: '2026-02-20T10:00:00+07:00',
      reason: 'Treadmill test',
      status: 'scheduled',
    },
    {
      id: 'a9',
      patientId: 'p9',
      date: '2026-02-21T09:00:00+07:00',
      reason: 'Uji tusuk kulit',
      status: 'scheduled',
    },
    {
      id: 'a10',
      patientId: 'p10',
      date: '2026-02-15T11:00:00+07:00',
      reason: 'Review lab',
      status: 'scheduled',
    },
  ]);

  await knex('workflow_steps').insert([
    { id: 'wf-1', name: 'Registrasi' },
    { id: 'wf-2', name: 'Pemeriksaan' },
    { id: 'wf-3', name: 'Obat' },
    { id: 'wf-4', name: 'Pembayaran' },
  ]);
};
